Add a notebook on running romancal
spacetelescope/romancal-notebooks pull request #3
Opened 2021-10-20 19:59 UTC by nden

2021-10-25 19:20 UTC, sosey requested changes

2021-10-25 19:20 UTC, sosey commented on general/Running the Roman pipeline.ipynb
> +    "```\n",
do we want to mention here that the test server isn't public, but that this is the way to set it? Also mention that offline, the crds cache path is used by the installed crds client? and maybe that when the server is referenced, missing reference files that are required are downloaded and installed in the cache?

2021-10-25 19:20 UTC, sosey commented on general/Running the Roman pipeline.ipynb
> +    "level1_file = \"/grp/roman/scsb/build_0.3/l1_0004_science_raw.asdf\"\n",
shall we make this for a general raw file that we make available in box?

2021-10-25 19:20 UTC, sosey commented on general/Running the Roman pipeline.ipynb
> +    "level2_file = \"/grp/roman/scsb/build_0.3/l2_0004_rate.asdf\""
same generalization comment as above for the input level 1 file

2021-10-25 19:20 UTC, sosey commented on general/Running the Roman pipeline.ipynb
> +    "### Running a step with local reference files\n",
Do we want to also include an example of using the code in a python env directly? i.e. not calling stpipe, but importing the step?

2021-12-05 19:53 UTC, nden commented on general/Running the Roman pipeline.ipynb
> +    "level1_file = \"/grp/roman/scsb/build_0.3/l1_0004_science_raw.asdf\"\n",
I updated the uncal file in Box with the latest version and added a generated L2 file.

2021-12-05 19:53 UTC, nden commented on general/Running the Roman pipeline.ipynb
> +    "level2_file = \"/grp/roman/scsb/build_0.3/l2_0004_rate.asdf\""
next cell?

2021-12-14 01:37 UTC, sosey commented
@nden  I had to move the location of the box folder, so we need to update the data links

2021-12-14 19:35 UTC, nden commented
@sosey I believe I addressed all comments.

2021-12-14 19:45 UTC, sosey approved these changes

2021-12-14 19:59 UTC, merged